---
abstract: 'RT Authentication using External Sources'
author:
  - 'Mike Peachey'
  - 'Mike Peachey <zordrak@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Authen-ExternalAuth
no_index:
  directory:
    - etc
    - html
    - inc
    - xt
recommends:
  CGI::Cookie: 0
  DBI: 0
  Net::LDAP: 0
  Net::SSLeay: 0
requires:
  CGI::Cookie: 0
  DBI: 0
  Net::LDAP: 0
  Net::SSLeay: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.17
